server {
    listen 80;
    server_name bokhar.online www.bokhar.online;
    client_max_body_size 20M;

    # ۱. فرانت‌اکند ری‌اکت
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # ۲. هدایت ترافیک API، ادمین و متریکس به کانتینر جنگو
    location ~ ^/(api|admin|metrics)/ {
        proxy_pass http://backend:8000; # نام سرویس کامپوز
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # ۳. فایل‌های استاتیک پنل ادمین و داکیومنت‌ها (خوانده شده از Volume مشترک)
    location /static/ {
        alias /app/staticfiles/;
        expires 30d;
        access_log off;
    }

    # ۴. عکس‌های آپلود شده محصولات (خوانده شده از Volume مشترک)
    location /media/ {
        alias /app/media/;
        expires 30d;
        access_log off;
    }
}