# Generated by Django 5.2.9 on 2026-06-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_ticket_ticketmessage_usersession"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="user_full_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="نام کاربر"
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="user_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="شماره تماس کاربر"
            ),
        ),
        migrations.AddField(
            model_name="ticketmessage",
            name="sender_full_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="نام فرستنده"
            ),
        ),
        migrations.AddField(
            model_name="ticketmessage",
            name="sender_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="شماره تماس فرستنده"
            ),
        ),
    ]
