# Generated by Django 5.2.9 on 2026-06-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_ticket_user_full_name_ticket_user_phone_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersession",
            options={
                "ordering": ["-last_used"],
                "verbose_name": "نشست کاربر",
                "verbose_name_plural": "نشست\u200cهای کاربر",
            },
        ),
        migrations.AddField(
            model_name="usersession",
            name="browser_version",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="نسخه مرورگر"
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="device_brand",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="برند دستگاه"
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="device_model",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="مدل دستگاه"
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="device_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="نام دستگاه"
            ),
        ),
        migrations.AddField(
            model_name="usersession",
            name="os_version",
            field=models.CharField(blank=True, max_length=50, verbose_name="نسخه OS"),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="browser",
            field=models.CharField(blank=True, max_length=100, verbose_name="مرورگر"),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="device",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="دستگاه (User-Agent)"
            ),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="os",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="سیستم عامل"
            ),
        ),
    ]
