# Generated by Django 5.2.9 on 2026-07-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_usersession_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="device_fingerprint",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="شناسه دستگاه"
            ),
        ),
    ]
