# Generated by Django 5.2.9 on 2026-07-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_usersession_device_fingerprint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "تیکت",
                "verbose_name_plural": "تیکت\u200cها",
            },
        ),
        migrations.AlterModelOptions(
            name="ticketmessage",
            options={
                "ordering": ["created_at"],
                "verbose_name": "پیام تیکت",
                "verbose_name_plural": "پیام\u200cهای تیکت",
            },
        ),
        migrations.AddField(
            model_name="ticketmessage",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="ticket_files/%Y/%m/",
                verbose_name="فایل پیوست",
            ),
        ),
        migrations.AddField(
            model_name="ticketmessage",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="نام فایل"),
        ),
        migrations.AddField(
            model_name="ticketmessage",
            name="file_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("image", "تصویر"),
                    ("video", "ویدیو"),
                    ("audio", "صوت"),
                    ("file", "فایل"),
                    ("location", "موقعیت مکانی"),
                ],
                max_length=20,
                verbose_name="نوع فایل",
            ),
        ),
        migrations.AddField(
            model_name="ticketmessage",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="ticketmessage",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=11, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "باز"),
                    ("answered", "پاسخ داده شده"),
                    ("closed", "بسته"),
                ],
                default="open",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="subject",
            field=models.CharField(max_length=255, verbose_name="موضوع"),
        ),
        migrations.AlterField(
            model_name="ticketmessage",
            name="body",
            field=models.TextField(blank=True, verbose_name="متن پیام"),
        ),
        migrations.AlterField(
            model_name="ticketmessage",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="از طرف ادمین"),
        ),
    ]
