# Generated by Django 5.2.9 on 2026-07-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_ticket_options_alter_ticketmessage_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticketmessage",
            name="file_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="نام فایل"
            ),
        ),
    ]
