# Generated by Django 5.2.9 on 2026-08-15 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_ticketmessage_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="apartment_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="پلاک/ساختمان"
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="unit",
            field=models.PositiveIntegerField(default=1, verbose_name="واحد"),
        ),
    ]
