# Generated by Django 5.2.9 on 2026-08-15 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_address_apartment_name_address_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="عنوان آدرس (مثلاً خانه، محل کار)",
            ),
        ),
    ]
