# Generated by Django 5.2.9 on 2026-08-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_address_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="usage_count",
            field=models.PositiveIntegerField(default=0, verbose_name="تعداد استفاده"),
        ),
    ]
