name: Deploy to VPS

on:
  push:
    branches:
      - master
permissions:
  contents: write        # ← این رو اضافه کن
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build images
        run: |
          docker build -t backend:latest ./backend
          docker build -t frontend:latest ./Bokhar-Frontend

      - name: Save and compress
        run: |
          docker save backend:latest | gzip > backend.tar.gz
          docker save frontend:latest | gzip > frontend.tar.gz

      - name: Delete old release
        run: |
          gh release delete deploy-latest --yes || true
          git push origin :refs/tags/deploy-latest || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: deploy-latest
          name: "Latest Deploy"
          files: |
            backend.tar.gz
            frontend.tar.gz
            docker-compose.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}